# Generated by Django 3.0.5 on 2020-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_auto_20200428_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
