# Generated by Django 3.0.5 on 2020-05-01 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messanger', '0005_auto_20200501_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_readed',
            field=models.ManyToManyField(related_name='readed', to=settings.AUTH_USER_MODEL, verbose_name='Прочитаено'),
        ),
    ]
