# Generated by Django 3.0.5 on 2020-05-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messanger', '0006_auto_20200501_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_readed',
            field=models.ManyToManyField(related_name='readed', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
