# Generated by Django 3.0.5 on 2020-05-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0009_auto_20200505_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Преподаватель', 'Преподаватель'), ('Учащийся', 'Учащийся')], default='Учищайся', max_length=30),
        ),
    ]
