# Generated by Django 3.0.5 on 2020-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0010_auto_20200505_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Преподаватель', 'Преподаватель'), ('Учащийся', 'Учащийся')], max_length=30),
        ),
    ]
